name: firefinder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.1.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.1
  flutter:
    sdk: flutter
  provider: ^6.1.1
  timeago: ^3.7.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/fires/
